CREATE TABLE IF NOT EXISTS sales_person (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at      TIMESTAMP DEFAULT NOW(),
  code            TEXT UNIQUE NOT NULL,
  name            TEXT NOT NULL,
  start_work_date DATE
);

ALTER TABLE invoice
  ADD COLUMN IF NOT EXISTS sales_person_id BIGINT REFERENCES sales_person(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

INSERT INTO sales_person (id, created_at, code, name, start_work_date)
VALUES 
  (1, '2026-01-01 00:00:00+00', 'SP001', 'Somchai Jaidee', '2025-01-15'),
  (2, '2026-01-01 00:00:00+00', 'SP002', 'Somsak Rakchart', '2025-02-01'),
  (3, '2026-01-02 00:00:00+00', 'SP003', 'Wipawee Sangdow', '2025-03-10'),
  (4, '2026-01-05 00:00:00+00', 'SP004', 'Ananda Everest', '2025-05-20'),
  (5, '2026-01-10 00:00:00+00', 'SP005', 'Kanya Phisut', '2025-06-01'),
  (6, '2026-01-12 00:00:00+00', 'SP006', 'Chaiwat Wangdee', '2025-07-15'),
  (7, '2026-01-15 00:00:00+00', 'SP007', 'Nattha Siri', '2025-08-22'),
  (8, '2026-01-20 00:00:00+00', 'SP008', 'Piti Chokdee', '2025-09-01'),
  (9, '2026-01-25 00:00:00+00', 'SP009', 'Manee Meesook', '2025-10-10'),
  (10, '2026-02-01 00:00:00+00', 'SP010', 'Tanachai Rungruang', '2025-11-05') 
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('sales_person', 'id'), coalesce(max(id), 0) + 1, false) FROM sales_person;
